tasks:
  - name: cfn
    before: |
      pip install cfn-lint
      cargo install cfn-guard
      gem install cfn-toml
      gem install aws_s3_website_sync
      gem install dotenv
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT

    command: |
      export GITPOD_IP=$(curl ifconfig.me)
      source "$THEIA_WORKSPACE_ROOT/bin/rds/update-sg-rule"

  - name: npm-init
    command: |
      ruby "$THEIA_WORKSPACE_ROOT/bin/frontend/generate-env"
      cd "$THEIA_WORKSPACE_ROOT/frontend-react-js"
      npm i 

  - name: postgres
    before: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev

  - name: flask
    command: |
      ruby "$THEIA_WORKSPACE_ROOT/bin/backend/generate-env"
      cd "$THEIA_WORKSPACE_ROOT/backend-flask/"
      pip install -r requirements.txt

  - name: fargate
    command: |
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      sudo dpkg -i session-manager-plugin.deb
      rm session-manager-plugin.deb

  - name: cdk
    before: |
      npm install aws-cdk -g
      cd "$THEIA_WORKSPACE_ROOT/thumbing-serverless-cdk"
      cp .env.example .env
      npm i
      cdk bootstrap "aws://$AWS_ACCOUNT_ID/$AWS_DEFAULT_REGION"
      cd "$THEIA_WORKSPACE_ROOT/aws/lambdas/process-images"
      npm i
      
  - name: aws-sam
    init: |
      cd /workspace
      wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
      sudo ./sam-installation/install
      cd $THEIA_WORKSPACE_ROOT

ports:
  - port: 3000
    name: Frontend-react-js
    visibility: public
  - port: 4567
    name: Backend-flask
    visibility: public
  - port: 4318
    name: otel-collector
    visibility: public

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - cweijan.vscode-postgresql-client2
    - dsteenman.cloudformation-yaml-snippets
